Fix Keyboard and Input elements
rdkcentral/solid-ui pull request #50
Opened 2024-09-24 14:38 UTC by francescochiapello

## Description

- Receive keyboard formats from element props
- Apply style and textStyle to Input element

2024-09-24 14:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/solid-ui?pullRequest=50) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/solid-ui?pullRequest=50) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/solid-ui?pullRequest=50) it.</sub>

2024-09-24 16:05 UTC, cee-money requested changes
Thanks for contributing @francescochiapello 🚀 👏 

I just suggested a couple changes. Would you mind filling out the PR description with a few more details to help reviewers understand your main goal with this PR? I see that we wanted to be able to style the text in the `Input` component, but I'm less clear on what we're tackling with the `Keyboard` changes. Thanks again!

2024-09-25 08:34 UTC, francescochiapello commented on packages/solid/components/Input/Input.types.ts
> +
I'm not sure about that, I mean that `style` prop is not recognised by ts.

![style](https://github.com/user-attachments/assets/56012698-2799-44d0-80da-17024d5eeebe)

2024-09-25 15:28 UTC, cee-money commented on packages/solid/components/Input/Input.types.ts
> +
what version of `@lightningtv/solid-ui` do you happen to be on? i'm not seeing this type error when using the latest [`@lightningtv/solid-ui@0.29.1`](https://github.com/rdkcentral/solid-ui/releases/tag/%40lightningtv%2Fsolid-ui%400.29.1)

2024-09-27 15:39 UTC, anthony9187 commented on packages/solid/components/Input/Input.types.ts
> +  textStyle?: TextStyles;
can we update `@lightningtv/solid` import to include `TextStyles` as well? This isn't currently imported

2024-09-27 15:43 UTC, anthony9187 requested changes
@francescochiapello thanks again for taking your time to contribute to our project! Just one more request - can you update the PR title to use the following format:
```
fix: <description>
```

our versioning system uses conventional commits to handle version bumps and it'll break without the proper casing/punctuation

2024-10-28 13:52 UTC, anthony9187 commented
Hi @francescochiapello! This has been sitting stale for a while so I'm gonna go ahead and close it for now. If you're interested in re-opening this please feel free to do so, or reach out to us either via an issue or discord. Thanks!

2024-10-28 13:52 UTC, closed without merging